---
    - name: Clone project
      git:
        repo: https://github.com/GoContainer/Sweady.git
        dest: /tmp/sweady
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Ensures data dir exists
      file: path=/var/lib/docker/volumes/monitoring_prometheus_config/_data/ state=directory
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Config for Prometheus
      copy:
        src: ../docker-compose/monitoring/prometheus/prometheus.yml
        dest: /var/lib/docker/volumes/monitoring_prometheus_config/_data/prometheus.yml
        owner: root
        group: root
        mode: 0755
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Data for Logstash
      file: path=/var/lib/docker/volumes/log_logstash_config/_data/  state=directory
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Config for Logstash
      copy:
        src: ../docker-compose/log/conf/gelf.conf
        dest: /var/lib/docker/volumes/log_logstash_config/_data/gelf.yml
        owner: root
        group: root
        mode: 0755
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Sleep
      command: sleep 30
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy Sweady stack
      command: docker stack deploy -c /tmp/sweady/docker-compose/sweady/docker-compose.yml sweady
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy logging stack
      command: docker stack deploy -c /tmp/sweady/docker-compose/log/docker-compose.yml log
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy monitoring stack
      command: docker stack deploy -c /tmp/sweady/docker-compose/monitoring/docker-compose.yml monitoring
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Sleep
      command: sleep 30
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy Grafana Datasource
      command: "curl -X POST http://127.0.0.1:3000/api/datasources --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/docker-compose/monitoring/grafana/datasource/prometheus.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy Grafana Dashboard -> Docker
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/docker-compose/monitoring/grafana/dashboards/docker_monitoring.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy Grafana Dashboard -> Prometheus
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/docker-compose/monitoring/grafana/dashboards/prometheus.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Deploy Grafana Dashboard -> Docker Swarm
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'content-Type: application/json' --data-binary '@/tmp/sweady/docker-compose/monitoring/grafana/dashboards/docker_swarm.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"